CREATE TABLE IF NOT EXISTS tipo_cambio (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  moneda_origen VARCHAR(255) NOT NULL,
  moneda_destino VARCHAR(255) NOT NULL,
  tipo_cambio DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL
);